// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUISpecFlowBootstrap.UIMaps.CalculatorClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class Calculator
    {
        
        #region Properties
        public UICalculatorWindow UICalculatorWindow
        {
            get
            {
                if ((this.mUICalculatorWindow == null))
                {
                    this.mUICalculatorWindow = new UICalculatorWindow();
                }
                return this.mUICalculatorWindow;
            }
        }
        #endregion
        
        #region Fields
        private UICalculatorWindow mUICalculatorWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICalculatorWindow : WinWindow
    {
        
        public UICalculatorWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Калькулятор";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "CalcFrame";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public UIMenuBar UIMenuBar
        {
            get
            {
                if ((this.mUIMenuBar == null))
                {
                    this.mUIMenuBar = new UIMenuBar(this);
                }
                return this.mUIMenuBar;
            }
        }
        
        public UIResultTextControl UIResultTextControl
        {
            get
            {
                if ((this.mUIResultTextControl == null))
                {
                    this.mUIResultTextControl = new UIResultTextControl(this);
                }
                return this.mUIResultTextControl;
            }
        }
        
        public UIMCButtonControl UIMCButtonControl
        {
            get
            {
                if ((this.mUIMCButtonControl == null))
                {
                    this.mUIMCButtonControl = new UIMCButtonControl(this);
                }
                return this.mUIMCButtonControl;
            }
        }
        
        public UIMRButtonControl UIMRButtonControl
        {
            get
            {
                if ((this.mUIMRButtonControl == null))
                {
                    this.mUIMRButtonControl = new UIMRButtonControl(this);
                }
                return this.mUIMRButtonControl;
            }
        }
        
        public UIMSButtonControl UIMSButtonControl
        {
            get
            {
                if ((this.mUIMSButtonControl == null))
                {
                    this.mUIMSButtonControl = new UIMSButtonControl(this);
                }
                return this.mUIMSButtonControl;
            }
        }
        
        public UIMPlusButtonControl UIMPlusButtonControl
        {
            get
            {
                if ((this.mUIMPlusButtonControl == null))
                {
                    this.mUIMPlusButtonControl = new UIMPlusButtonControl(this);
                }
                return this.mUIMPlusButtonControl;
            }
        }
        
        public UIMMinusButtonControl UIMMinusButtonControl
        {
            get
            {
                if ((this.mUIMMinusButtonControl == null))
                {
                    this.mUIMMinusButtonControl = new UIMMinusButtonControl(this);
                }
                return this.mUIMMinusButtonControl;
            }
        }
        
        public UIBackspaceButtonControl UIBackspaceButtonControl
        {
            get
            {
                if ((this.mUIBackspaceButtonControl == null))
                {
                    this.mUIBackspaceButtonControl = new UIBackspaceButtonControl(this);
                }
                return this.mUIBackspaceButtonControl;
            }
        }
        
        public UICEButtonControl UICEButtonControl
        {
            get
            {
                if ((this.mUICEButtonControl == null))
                {
                    this.mUICEButtonControl = new UICEButtonControl(this);
                }
                return this.mUICEButtonControl;
            }
        }
        
        public UICButtonControl UICButtonControl
        {
            get
            {
                if ((this.mUICButtonControl == null))
                {
                    this.mUICButtonControl = new UICButtonControl(this);
                }
                return this.mUICButtonControl;
            }
        }
        
        public UIUnarMinusButtonControl UIUnarMinusButtonControl
        {
            get
            {
                if ((this.mUIUnarMinusButtonControl == null))
                {
                    this.mUIUnarMinusButtonControl = new UIUnarMinusButtonControl(this);
                }
                return this.mUIUnarMinusButtonControl;
            }
        }
        
        public UISquareRootButtonControl UISquareRootButtonControl
        {
            get
            {
                if ((this.mUISquareRootButtonControl == null))
                {
                    this.mUISquareRootButtonControl = new UISquareRootButtonControl(this);
                }
                return this.mUISquareRootButtonControl;
            }
        }
        
        public UIDivisionButtonControl UIDivisionButtonControl
        {
            get
            {
                if ((this.mUIDivisionButtonControl == null))
                {
                    this.mUIDivisionButtonControl = new UIDivisionButtonControl(this);
                }
                return this.mUIDivisionButtonControl;
            }
        }
        
        public UIPercentButtonControl UIPercentButtonControl
        {
            get
            {
                if ((this.mUIPercentButtonControl == null))
                {
                    this.mUIPercentButtonControl = new UIPercentButtonControl(this);
                }
                return this.mUIPercentButtonControl;
            }
        }
        
        public UIMultiplicationButtonControl UIMultiplicationButtonControl
        {
            get
            {
                if ((this.mUIMultiplicationButtonControl == null))
                {
                    this.mUIMultiplicationButtonControl = new UIMultiplicationButtonControl(this);
                }
                return this.mUIMultiplicationButtonControl;
            }
        }
        
        public UIInverseButtonControl UIInverseButtonControl
        {
            get
            {
                if ((this.mUIInverseButtonControl == null))
                {
                    this.mUIInverseButtonControl = new UIInverseButtonControl(this);
                }
                return this.mUIInverseButtonControl;
            }
        }
        
        public UIMinusButtonControl UIMinusButtonControl
        {
            get
            {
                if ((this.mUIMinusButtonControl == null))
                {
                    this.mUIMinusButtonControl = new UIMinusButtonControl(this);
                }
                return this.mUIMinusButtonControl;
            }
        }
        
        public UIPlusButtonControl UIPlusButtonControl
        {
            get
            {
                if ((this.mUIPlusButtonControl == null))
                {
                    this.mUIPlusButtonControl = new UIPlusButtonControl(this);
                }
                return this.mUIPlusButtonControl;
            }
        }
        
        public UIDecimalSeparatorButtonControl UIDecimalSeparatorButtonControl
        {
            get
            {
                if ((this.mUIDecimalSeparatorButtonControl == null))
                {
                    this.mUIDecimalSeparatorButtonControl = new UIDecimalSeparatorButtonControl(this);
                }
                return this.mUIDecimalSeparatorButtonControl;
            }
        }
        
        public UIResultButtonControl UIResultButtonControl
        {
            get
            {
                if ((this.mUIResultButtonControl == null))
                {
                    this.mUIResultButtonControl = new UIResultButtonControl(this);
                }
                return this.mUIResultButtonControl;
            }
        }
        
        public UIZeroButtonControl UIZeroButtonControl
        {
            get
            {
                if ((this.mUIZeroButtonControl == null))
                {
                    this.mUIZeroButtonControl = new UIZeroButtonControl(this);
                }
                return this.mUIZeroButtonControl;
            }
        }
        
        public UIOneButtonControl UIOneButtonControl
        {
            get
            {
                if ((this.mUIOneButtonControl == null))
                {
                    this.mUIOneButtonControl = new UIOneButtonControl(this);
                }
                return this.mUIOneButtonControl;
            }
        }
        
        public UITwoButtonControl UITwoButtonControl
        {
            get
            {
                if ((this.mUITwoButtonControl == null))
                {
                    this.mUITwoButtonControl = new UITwoButtonControl(this);
                }
                return this.mUITwoButtonControl;
            }
        }
        
        public UIThreeButtonControl UIThreeButtonControl
        {
            get
            {
                if ((this.mUIThreeButtonControl == null))
                {
                    this.mUIThreeButtonControl = new UIThreeButtonControl(this);
                }
                return this.mUIThreeButtonControl;
            }
        }
        
        public UIFourButtonControl UIFourButtonControl
        {
            get
            {
                if ((this.mUIFourButtonControl == null))
                {
                    this.mUIFourButtonControl = new UIFourButtonControl(this);
                }
                return this.mUIFourButtonControl;
            }
        }
        
        public UIFiveButtonControl UIFiveButtonControl
        {
            get
            {
                if ((this.mUIFiveButtonControl == null))
                {
                    this.mUIFiveButtonControl = new UIFiveButtonControl(this);
                }
                return this.mUIFiveButtonControl;
            }
        }
        
        public UISixButtonControl UISixButtonControl
        {
            get
            {
                if ((this.mUISixButtonControl == null))
                {
                    this.mUISixButtonControl = new UISixButtonControl(this);
                }
                return this.mUISixButtonControl;
            }
        }
        
        public UISevenButtonControl UISevenButtonControl
        {
            get
            {
                if ((this.mUISevenButtonControl == null))
                {
                    this.mUISevenButtonControl = new UISevenButtonControl(this);
                }
                return this.mUISevenButtonControl;
            }
        }
        
        public UIEightButtonControl UIEightButtonControl
        {
            get
            {
                if ((this.mUIEightButtonControl == null))
                {
                    this.mUIEightButtonControl = new UIEightButtonControl(this);
                }
                return this.mUIEightButtonControl;
            }
        }
        
        public UINineButtonControl UINineButtonControl
        {
            get
            {
                if ((this.mUINineButtonControl == null))
                {
                    this.mUINineButtonControl = new UINineButtonControl(this);
                }
                return this.mUINineButtonControl;
            }
        }
        
        public UIRadioButtonWindow UIRadioButtonWindow
        {
            get
            {
                if ((this.mUIRadioButtonWindow == null))
                {
                    this.mUIRadioButtonWindow = new UIRadioButtonWindow(this);
                }
                return this.mUIRadioButtonWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMenuBar mUIMenuBar;
        
        private UIResultTextControl mUIResultTextControl;
        
        private UIMCButtonControl mUIMCButtonControl;
        
        private UIMRButtonControl mUIMRButtonControl;
        
        private UIMSButtonControl mUIMSButtonControl;
        
        private UIMPlusButtonControl mUIMPlusButtonControl;
        
        private UIMMinusButtonControl mUIMMinusButtonControl;
        
        private UIBackspaceButtonControl mUIBackspaceButtonControl;
        
        private UICEButtonControl mUICEButtonControl;
        
        private UICButtonControl mUICButtonControl;
        
        private UIUnarMinusButtonControl mUIUnarMinusButtonControl;
        
        private UISquareRootButtonControl mUISquareRootButtonControl;
        
        private UIDivisionButtonControl mUIDivisionButtonControl;
        
        private UIPercentButtonControl mUIPercentButtonControl;
        
        private UIMultiplicationButtonControl mUIMultiplicationButtonControl;
        
        private UIInverseButtonControl mUIInverseButtonControl;
        
        private UIMinusButtonControl mUIMinusButtonControl;
        
        private UIPlusButtonControl mUIPlusButtonControl;
        
        private UIDecimalSeparatorButtonControl mUIDecimalSeparatorButtonControl;
        
        private UIResultButtonControl mUIResultButtonControl;
        
        private UIZeroButtonControl mUIZeroButtonControl;
        
        private UIOneButtonControl mUIOneButtonControl;
        
        private UITwoButtonControl mUITwoButtonControl;
        
        private UIThreeButtonControl mUIThreeButtonControl;
        
        private UIFourButtonControl mUIFourButtonControl;
        
        private UIFiveButtonControl mUIFiveButtonControl;
        
        private UISixButtonControl mUISixButtonControl;
        
        private UISevenButtonControl mUISevenButtonControl;
        
        private UIEightButtonControl mUIEightButtonControl;
        
        private UINineButtonControl mUINineButtonControl;
        
        private UIRadioButtonWindow mUIRadioButtonWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMenuBar : WinMenuBar
    {
        
        public UIMenuBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenu.PropertyNames.Name] = "Приложение";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public UIViewMenuItem UIViewMenuItem
        {
            get
            {
                if ((this.mUIViewMenuItem == null))
                {
                    this.mUIViewMenuItem = new UIViewMenuItem(this);
                }
                return this.mUIViewMenuItem;
            }
        }
        
        public WinMenuItem UIEditMenuItem
        {
            get
            {
                if ((this.mUIEditMenuItem == null))
                {
                    this.mUIEditMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIEditMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Правка";
                    this.mUIEditMenuItem.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIEditMenuItem;
            }
        }
        
        public WinMenuItem UIHelpMenuItem
        {
            get
            {
                if ((this.mUIHelpMenuItem == null))
                {
                    this.mUIHelpMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIHelpMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Справка";
                    this.mUIHelpMenuItem.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIHelpMenuItem;
            }
        }

        public WinMenuItem UIViewMenuIngineerItem
        {
            get
            {
                if ((this.mUIViewMenuIngineerItem == null))
                {
                    this.mUIViewMenuIngineerItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIViewMenuIngineerItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Инженерный\tAlt+2";
                    this.mUIViewMenuIngineerItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIViewMenuIngineerItem.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIViewMenuIngineerItem;
            }
        }

        public WinMenuItem UIViewMenuSimpleItem
        {
            get
            {
                if ((this.mUIViewMenuSimpleItem == null))
                {
                    this.mUIViewMenuSimpleItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIViewMenuSimpleItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Обычный\tAlt+1";
                    this.mUIViewMenuSimpleItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIViewMenuSimpleItem.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIViewMenuSimpleItem;
            }
        }

        public WinMenuItem UIViewMenuProgrammerItem
        {
            get
            {
                if ((this.mUIViewMenuProgrammerItem == null))
                {
                    this.mUIViewMenuProgrammerItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIViewMenuProgrammerItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Программист\tAlt+3";
                    this.mUIViewMenuProgrammerItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIViewMenuProgrammerItem.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIViewMenuProgrammerItem;
            }
        }

        public WinMenuItem UIViewMenuStatisticItem
        {
            get
            {
                if ((this.mUIViewMenuStatisticItem == null))
                {
                    this.mUIViewMenuStatisticItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIViewMenuStatisticItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Статистика\tAlt+4";
                    this.mUIViewMenuStatisticItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIViewMenuStatisticItem.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIViewMenuStatisticItem;
            }
        }
        #endregion
        
        #region Fields
        private UIViewMenuItem mUIViewMenuItem;
        
        private WinMenuItem mUIEditMenuItem;
        
        private WinMenuItem mUIHelpMenuItem;
        private WinMenuItem mUIViewMenuIngineerItem;
        private WinMenuItem mUIViewMenuSimpleItem;
        private WinMenuItem mUIViewMenuProgrammerItem;
        private WinMenuItem mUIViewMenuStatisticItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIViewMenuItem : WinMenuItem
    {
        
        public UIViewMenuItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenuItem.PropertyNames.Name] = "Вид";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
     
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIResultTextControl : WinWindow
    {
        
        public UIResultTextControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "150";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinText UIResultText
        {
            get
            {
                if ((this.mUIResultText == null))
                {
                    this.mUIResultText = new WinText(this);
                    #region Search Criteria
                    this.mUIResultText.SearchProperties[WinText.PropertyNames.Name] = "Результат";
                    this.mUIResultText.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIResultText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIResultText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMCButtonControl : WinWindow
    {
        
        public UIMCButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "122";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIMCButton
        {
            get
            {
                if ((this.mUIMCButton == null))
                {
                    this.mUIMCButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIMCButton.SearchProperties[WinButton.PropertyNames.Name] = "Очистка памяти";
                    this.mUIMCButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIMCButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIMCButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMRButtonControl : WinWindow
    {
        
        public UIMRButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "123";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIMRButton
        {
            get
            {
                if ((this.mUIMRButton == null))
                {
                    this.mUIMRButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIMRButton.SearchProperties[WinButton.PropertyNames.Name] = "Вызов из памяти";
                    this.mUIMRButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIMRButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIMRButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMSButtonControl : WinWindow
    {
        
        public UIMSButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "124";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIMSButton
        {
            get
            {
                if ((this.mUIMSButton == null))
                {
                    this.mUIMSButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIMSButton.SearchProperties[WinButton.PropertyNames.Name] = "Сохранение в памяти";
                    this.mUIMSButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIMSButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIMSButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMPlusButtonControl : WinWindow
    {
        
        public UIMPlusButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "125";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIMPlusButton
        {
            get
            {
                if ((this.mUIMPlusButton == null))
                {
                    this.mUIMPlusButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIMPlusButton.SearchProperties[WinButton.PropertyNames.Name] = "Добавление памяти";
                    this.mUIMPlusButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIMPlusButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIMPlusButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMMinusButtonControl : WinWindow
    {
        
        public UIMMinusButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "126";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIMMinusButton
        {
            get
            {
                if ((this.mUIMMinusButton == null))
                {
                    this.mUIMMinusButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIMMinusButton.SearchProperties[WinButton.PropertyNames.Name] = "Вычитание памяти";
                    this.mUIMMinusButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIMMinusButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIMMinusButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIBackspaceButtonControl : WinWindow
    {
        
        public UIBackspaceButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "83";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIBackspaceButton
        {
            get
            {
                if ((this.mUIBackspaceButton == null))
                {
                    this.mUIBackspaceButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIBackspaceButton.SearchProperties[WinButton.PropertyNames.Name] = "Backspace";
                    this.mUIBackspaceButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIBackspaceButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIBackspaceButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICEButtonControl : WinWindow
    {
        
        public UICEButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "82";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UICEButton
        {
            get
            {
                if ((this.mUICEButton == null))
                {
                    this.mUICEButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICEButton.SearchProperties[WinButton.PropertyNames.Name] = "Очистка записи";
                    this.mUICEButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUICEButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICEButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICButtonControl : WinWindow
    {
        
        public UICButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "81";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UICButton
        {
            get
            {
                if ((this.mUICButton == null))
                {
                    this.mUICButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICButton.SearchProperties[WinButton.PropertyNames.Name] = "Очистить";
                    this.mUICButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUICButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIUnarMinusButtonControl : WinWindow
    {
        
        public UIUnarMinusButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "80";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIUnarMinusButton
        {
            get
            {
                if ((this.mUIUnarMinusButton == null))
                {
                    this.mUIUnarMinusButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIUnarMinusButton.SearchProperties[WinButton.PropertyNames.Name] = "Унарный минус";
                    this.mUIUnarMinusButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIUnarMinusButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIUnarMinusButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UISquareRootButtonControl : WinWindow
    {
        
        public UISquareRootButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "110";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UISquareRootButton
        {
            get
            {
                if ((this.mUISquareRootButton == null))
                {
                    this.mUISquareRootButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISquareRootButton.SearchProperties[WinButton.PropertyNames.Name] = "Квадратный корень";
                    this.mUISquareRootButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUISquareRootButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISquareRootButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIDivisionButtonControl : WinWindow
    {
        
        public UIDivisionButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "91";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIDivisionButton
        {
            get
            {
                if ((this.mUIDivisionButton == null))
                {
                    this.mUIDivisionButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIDivisionButton.SearchProperties[WinButton.PropertyNames.Name] = "Деление";
                    this.mUIDivisionButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIDivisionButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIDivisionButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIPercentButtonControl : WinWindow
    {
        
        public UIPercentButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "118";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIPercentButton
        {
            get
            {
                if ((this.mUIPercentButton == null))
                {
                    this.mUIPercentButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIPercentButton.SearchProperties[WinButton.PropertyNames.Name] = "Процент";
                    this.mUIPercentButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIPercentButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIPercentButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMultiplicationButtonControl : WinWindow
    {
        
        public UIMultiplicationButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "92";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIMultiplicationButton
        {
            get
            {
                if ((this.mUIMultiplicationButton == null))
                {
                    this.mUIMultiplicationButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIMultiplicationButton.SearchProperties[WinButton.PropertyNames.Name] = "Умножение";
                    this.mUIMultiplicationButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIMultiplicationButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIMultiplicationButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIInverseButtonControl : WinWindow
    {
        
        public UIInverseButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "114";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIInverseButton
        {
            get
            {
                if ((this.mUIInverseButton == null))
                {
                    this.mUIInverseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIInverseButton.SearchProperties[WinButton.PropertyNames.Name] = "Обратная величина";
                    this.mUIInverseButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIInverseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIInverseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMinusButtonControl : WinWindow
    {
        
        public UIMinusButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "94";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIMinusButton
        {
            get
            {
                if ((this.mUIMinusButton == null))
                {
                    this.mUIMinusButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIMinusButton.SearchProperties[WinButton.PropertyNames.Name] = "Вычитание";
                    this.mUIMinusButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIMinusButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIMinusButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIPlusButtonControl : WinWindow
    {
        
        public UIPlusButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "93";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIPlusButton
        {
            get
            {
                if ((this.mUIPlusButton == null))
                {
                    this.mUIPlusButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIPlusButton.SearchProperties[WinButton.PropertyNames.Name] = "Сложение";
                    this.mUIPlusButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIPlusButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIPlusButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIDecimalSeparatorButtonControl : WinWindow
    {
        
        public UIDecimalSeparatorButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "84";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIDecimalSeparatorButton
        {
            get
            {
                if ((this.mUIDecimalSeparatorButton == null))
                {
                    this.mUIDecimalSeparatorButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIDecimalSeparatorButton.SearchProperties[WinButton.PropertyNames.Name] = "Десятичный разделитель";
                    this.mUIDecimalSeparatorButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIDecimalSeparatorButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIDecimalSeparatorButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIResultButtonControl : WinWindow
    {
        
        public UIResultButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "121";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIResultButton
        {
            get
            {
                if ((this.mUIResultButton == null))
                {
                    this.mUIResultButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIResultButton.SearchProperties[WinButton.PropertyNames.Name] = "Равно";
                    this.mUIResultButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIResultButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIResultButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIZeroButtonControl : WinWindow
    {
        
        public UIZeroButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "130";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIZeroButton
        {
            get
            {
                if ((this.mUIZeroButton == null))
                {
                    this.mUIZeroButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIZeroButton.SearchProperties[WinButton.PropertyNames.Name] = "0";
                    this.mUIZeroButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIZeroButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIZeroButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIOneButtonControl : WinWindow
    {
        
        public UIOneButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "131";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIOneButton
        {
            get
            {
                if ((this.mUIOneButton == null))
                {
                    this.mUIOneButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOneButton.SearchProperties[WinButton.PropertyNames.Name] = "1";
                    this.mUIOneButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIOneButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOneButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UITwoButtonControl : WinWindow
    {
        
        public UITwoButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "132";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UITwoButton
        {
            get
            {
                if ((this.mUITwoButton == null))
                {
                    this.mUITwoButton = new WinButton(this);
                    #region Search Criteria
                    this.mUITwoButton.SearchProperties[WinButton.PropertyNames.Name] = "2";
                    this.mUITwoButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUITwoButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUITwoButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIThreeButtonControl : WinWindow
    {
        
        public UIThreeButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "133";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIThreeButton
        {
            get
            {
                if ((this.mUIThreeButton == null))
                {
                    this.mUIThreeButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIThreeButton.SearchProperties[WinButton.PropertyNames.Name] = "3";
                    this.mUIThreeButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIThreeButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIThreeButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIFourButtonControl : WinWindow
    {
        
        public UIFourButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "134";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIFourButton
        {
            get
            {
                if ((this.mUIFourButton == null))
                {
                    this.mUIFourButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIFourButton.SearchProperties[WinButton.PropertyNames.Name] = "4";
                    this.mUIFourButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIFourButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIFourButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIFiveButtonControl : WinWindow
    {
        
        public UIFiveButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "135";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIFiveButton
        {
            get
            {
                if ((this.mUIFiveButton == null))
                {
                    this.mUIFiveButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIFiveButton.SearchProperties[WinButton.PropertyNames.Name] = "5";
                    this.mUIFiveButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIFiveButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIFiveButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UISixButtonControl : WinWindow
    {
        
        public UISixButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "136";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UISixButton
        {
            get
            {
                if ((this.mUISixButton == null))
                {
                    this.mUISixButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISixButton.SearchProperties[WinButton.PropertyNames.Name] = "6";
                    this.mUISixButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUISixButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISixButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UISevenButtonControl : WinWindow
    {
        
        public UISevenButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "137";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UISevenButton
        {
            get
            {
                if ((this.mUISevenButton == null))
                {
                    this.mUISevenButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISevenButton.SearchProperties[WinButton.PropertyNames.Name] = "7";
                    this.mUISevenButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUISevenButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISevenButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIEightButtonControl : WinWindow
    {
        
        public UIEightButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "138";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UIEightButton
        {
            get
            {
                if ((this.mUIEightButton == null))
                {
                    this.mUIEightButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIEightButton.SearchProperties[WinButton.PropertyNames.Name] = "8";
                    this.mUIEightButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIEightButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIEightButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UINineButtonControl : WinWindow
    {
        
        public UINineButtonControl(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "139";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinButton UINineButton
        {
            get
            {
                if ((this.mUINineButton == null))
                {
                    this.mUINineButton = new WinButton(this);
                    #region Search Criteria
                    this.mUINineButton.SearchProperties[WinButton.PropertyNames.Name] = "9";
                    this.mUINineButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUINineButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUINineButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIRadioButtonWindow : WinWindow
    {
        
        public UIRadioButtonWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "321";
            this.WindowTitles.Add("Калькулятор");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UIDegreeRadioButton
        {
            get
            {
                if ((this.mUIDegreeRadioButton == null))
                {
                    this.mUIDegreeRadioButton = new WinRadioButton(this);
                    #region Search Criteria
                    this.mUIDegreeRadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "Градусы";
                    this.mUIDegreeRadioButton.WindowTitles.Add("Калькулятор");
                    #endregion
                }
                return this.mUIDegreeRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUIDegreeRadioButton;
        #endregion
    }
}
